server:
    port: 8080
    contextPath: /
    app:
      disable-default-exception-handling: true
    error:
      whitelabel:
        enabled: false
endpoints:
      jmx:
        enabled: false
logging:
  level:
    org.springframework.security: ERROR